title: AdminTool
remote_theme: sighingnow/jekyll-gitbook
collections:
  pages:
    output: true
    sort_by: date
    permalink: /:collection/:year-:month-:day-:title:output_ext
  others:
    output: true
    sort_by: date
    permalink: /:collection/:year-:month-:day-:title:output_ext
plugins:
  - jekyll-feed
  - jekyll-seo-tag
